### ISSUE TITLE
Regressions from gym and tensorflow

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [ethz-asl/reinmav-gym#37]
This package no longer works with the latest openai/gym(`v0.15.4`) and tensorflow (`v2.0.0`)

Error from the latest gym environment:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jaeyoung/dev/reinmav-gym/gym_reinmav/run.py", line 11, in <module>
    from baselines.common.cmd_util import common_arg_parser, parse_unknown_args, make_vec_env, make_env
  File "/home/jaeyoung/dev/baselines/baselines/common/cmd_util.py", line 12, in <module>
    from gym.wrappers import FlattenDictWrapper
ImportError: cannot import name 'FlattenDictWrapper'
```

It is a shame that the CI was not able to catch this

**Comment by Jaeyoung-Lim** [comment]
Looks like the following combination of versions work:
  - `gym`: v1.12.1
  - `tensorflow-gpu`: v1.15
